name: MLI-Project

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/home

  ai:
    build: AI
    volumes:
      - ./AI:/home
    depends_on: 
      - db

  web:
    build: web
    volumes:
      - ./web:/home
    ports:
      - 8000:8501
    depends_on: 
      - ai

networks:
  default:  
    name: MLI_Network
    driver: bridge

volumes:
  pgdata: